export enum FranchisesEmissionSourceDataMethod {
  SPECIFIC_METHOD = "SPECIFIC-METHOD",
  NOT_SUB_METERED = "NOT-SUB-METERED",
  SAMPLE_GROUPS = "SAMPLE-GROUPS",
  AVERAGE_DATA_METHOD_FLOOR_SPACE = "AVERAGE-DATA-METHOD-FLOOR-SPACE",
  AVERAGE_DATA_METHOD_NOT_FLOOR_SPACE = "AVERAGE-DATA-METHOD-NOT-FLOOR-SPACE",

}