export enum UpstreamTransportationEmissionSourceDataMethod {
  FUEL_BASE_METHOD="FUEL-BASE-METHOD",
  DISTANCE_BASE_METHOD="DISTANCE-BASE-METHOD",
  SPEND_BASE_METHOD="SPEND-BASE-METHOD",
  SITE_SPECIFIC_METHOD = "SITE-SPECIFIC-METHOD",
  AVERAGE_DATA_METHOD = "AVERAGE-DATA-METHOD",
}